[package]
name = "fuse"
version = "0.1.0"
authors = ["kabeone <yacine.khemache@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuse = "0.3.1"
time = "0.1"
libc = "0.2.68"
